### PR TITLE
Adding aya and sura pages, Issue #499

### PR DESCRIPTION
**Pull request by sneetsher**

### CODE REVIEW

**Comment by sneetsher** [comment]
@assem-ch put back main tag. One thing are you following any coding style conventions. It will help much when trying to debug code.

**Comment by assem-ch** [comment]
@sneetsher PEP8 for python, HTML5 conventions for html, for Js no conventions for now.

I can help you to define what should be on the pages, and we can delegate the design specs to a designer.

**Comment by sneetsher** [comment]
Yes, if you could define what we should have in those pages, in #499

**Comment by assem-ch** [comment]
Here is a quick spec for the ayah detailed page:
https://github.com/Alfanous-team/alfanous/issues/503

**Comment by assem-ch** [comment]
The aya page now is partially implemented but as a search query:
https://www.alfanous.org/en/surah/As-Sajda/ayah/18

**Pull request closed without merging**
