### PR TITLE
Server version  (#483)

### PR DESCRIPTION
**Pull request by assem-ch**

### CODE REVIEW

**Comment by sneetsher** [comment]
@assem-ch what's going on, merging same changes? 

- Could make new clone in server from master.
- Backup current server version

then deploy any one using a symbolic link,  so we can test and switch back quickly if it's broken.

**Comment by assem-ch** [comment]
@sneetsher  the server version should be merged on master... through the years of inactivity i made some small fixes on server directly

You can install different version in server just by running `python scripts/update.py dev1/`

**Comment by sneetsher** [comment]
Ok avoid using git for this, it is not intended for this. (It uses the hashes to compare files & commits).

Make manual merge using meld which provide folder recursive diff. I mean to compare master & server with one level depth history. 

Apply changes to master and delete server. So we can keep track of it with clean merges

**Comment by assem-ch** [comment]
yes sure, server_version is temporary

**Pull request merged**
